language: php
sudo: false

git:
  depth: 3

matrix:
  include:
    - php: 7.1
    - php: 7.2
    - php: nightly
  fast_finish: true

cache:
  - vendor

before_script:
  - composer install --no-interaction

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
